" don't try to be vi compatible
set nocompatible

" Helps force plugins to load correctly when it is turned back on below
filetype off

" Load plugins here (pathogen or vundle)
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/.fzf
runtime! ftplugin/man.vim

call vundle#begin()

" Syntax
Plugin 'evidens/vim-twig'
Plugin 'groenewege/vim-less'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'othree/html5.vim'
Plugin 'tobyS/vmustache'
Plugin 'tomasr/molokai'

Plugin 'vimwiki/vimwiki'
Plugin 'wakatime/vim-wakatime'
Plugin 'w0rp/ale'
Plugin 'alvan/vim-php-manual'
Plugin 'Raimondi/delimitMate'
Plugin 'SirVer/ultisnips'
Plugin 'Valloric/YouCompleteMe'
Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'chriskempson/base16-vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'ervandew/supertab'
Plugin 'godlygeek/tabular'
Plugin 'honza/vim-snippets'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'joonty/vdebug'
Plugin 'junegunn/fzf.vim'
Plugin 'majutsushi/tagbar'
Plugin 'mattn/emmet-vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'terryma/vim-expand-region'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required

" Turn on syntax highlighting
syntax on

" For plugins to load correctly
filetype plugin indent on
filetype plugin on

" Pick a leader key
let mapleader = "\<space>"

" Remap jk to the Esc key
imap jk <Esc>

" Security
set modelines=0

" Show line numbers
set number
set relativenumber

set smartindent
set autoindent

" Show file stats
set ruler

" Persistent undo
set undodir=~/.vim_undodir
set undofile

" Encoding
set encoding=utf-8

" Whitespace
set nowrap
set textwidth=79
set formatoptions=cqrn1
set formatoptions-=t
set shiftwidth=4
set tabstop=4

" Cursor motion
set scrolloff=5
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Rendering
set ttyfast
set lazyredraw
set updatetime=350
set cursorline

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader>c :let @/=''<cr> " clear search

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
map <leader>l :set list!<CR> " Toggle tabs and EOL

set termguicolors
set background=dark
colorscheme molokai

" Random leader things
nmap <leader><tab> :b#<CR>
nmap <leader>ff :Files<CR>
nmap <leader>ft :NERDTreeToggle<CR>
nmap <leader>bb :Buffers<CR>
nmap <leader>tt :TagbarOpenAutoClose<CR>
nmap <leader>j :%!python -m json.tool<CR>
nmap <leader>ve :tabedit ~/.vimrc<CR>
nmap <leader>vr :so $MYVIMRC<CR>
nmap <silent><Leader><C-]> <C-w><C-]><C-w>T

let g:vimwiki_list = [
			\{'path': '~/Dropbox/VimWiki/personal.wiki'},
			\{'path': '~/Dropbox/VimWiki/work.wiki'}
			\]

" Random things
let NERDTreeQuitOnOpen=1
let g:nerdtree_tabs_open_on_gui_startup=2
let g:gitgutter_sign_column_always = 1
set noswapfile
set cursorline
set tags=tags;/
let g:vdebug_options= {
			\    "port" : 9999,
			\}

set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
set hidden

" YouCompleteMe and UltiSnips compatibility
let g:SuperTabDefaultCompletionType    = '<C-n>'
let g:SuperTabCrMapping                = 0

" YouCompleteMe
let g:ycm_key_list_select_completion   = ['<C-j>', '<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<C-p>', '<Up>']

let g:UltiSnipsSnippetDirectories=["UltiSnips", $HOME.'/.vim/Snippets']

" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/vendors/*,*/tmp/*,*/web/js/*,*/web/css/*
